version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=students
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=principal
    volumes:
      - school-db-data:/var/lib/postgresql/data
      - ./database_init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
volumes:
  school-db-data: